version: '3'
services: 
    client:
        container_name: client
        image: nginx
        volumes: 
            - ../client:/usr/share/nginx/html/
        ports: 
            - 80:80
    db:
        container_name: mysql
        image: mysql:5.6
        volumes:
          - ../data/mysql:/var/lib/mysql
        restart: always
        ports:
          - "3306:3306"
        environment:
          - MYSQL_ROOT_PASSWORD=chkdsk
          - MYSQL_DATABASE=notes_db
          - MYSQL_USER=root
          - MYSQL_PASSWORD=chkdsk
    phpmyadmin:
        container_name: phpmyadmin-cnt
        image: phpmyadmin/phpmyadmin:latest
        links:
            - db
        ports:
            - 8080:80
        depends_on:
            - db
        environment:
            - PMA_ARBITRARY=1
            - MYSQL_ROOT_PASSWORD=chkdsk
            - MYSQL_USER=root
            - MYSQL_PASSWORD=chkdsk